### PR TITLE
Optimize Diff creation

### PR DESCRIPTION
**Pull request by badetitou**
By commits

1. I created tests for `GLPHEDiffRange>>#newFrom`. And optimize this method a bit. I basically killed one string duplication
2. same for `GLPHEChange`. My bench show two times faster

### CODE REVIEW

**Comment by badetitou** [comment]
The last commit try to intriduce an optimization of the `addAll:unless:` method.
Here is the script I used to benchmark the update 

```st
users := OrderedCollection new.
1 to: 300 do: [ :idx |
	| user |
	user := GLHUser new.
	user id: idx. 
	users add: user ].

[	user2b := GLHUser new.
	user2b id: 298.
	user3b := GLHUser new.
	user3b id: 300.
	user4 := GLHUser new.
	user4 id: 302.

	result := users
		          addAll: {
				          user2b.
				          user3b.
				          user4 }
		          unless: [ :a :b | a id = b id ]] bench
"Before"
"'14 437.625 per second'"
"'16 029.394 per second'"
"After"
"'48 639.688 per second'"
"'44 872.426 per second'"
```

**Comment by alkalinan** [comment]
I am nicolas and I provide these commits !

**Comment by guillep** [comment]
Hi Nicolas! :)

**Comment by badetitou** [comment]
Hi Nicolas :)

**Review by alkalinan — APPROVED** [review]
I approve this commit !

**Comment by NicolasAnquetil** [comment]
I am nicolas and I approve this message ;-)

**Pull request merged**
